my $gen3 = load("gen3.poly");
my $f0 = $gen3->fcosheaf(0);
my $f1 = $gen3->fcosheaf(1);
my $us0 = $gen3->usual_chain_complex($f0);
my $us1 = $gen3->usual_chain_complex($f1);
my $bm0 = $gen3->borel_moore_complex($f0);
my $bm1 = $gen3->borel_moore_complex($f1);
my @result = ();
push @result, new Vector<Int>(topaz::betti_numbers($us0));
push @result, new Vector<Int>(topaz::betti_numbers($us1));
push @result, new Vector<Int>(topaz::betti_numbers($bm0));
push @result, new Vector<Int>(topaz::betti_numbers($bm1));
my $computed = new Matrix<Int>(@result);
my $desired = new Matrix<Int>([1,3],[14,0],[0,14],[3,1]);
compare_values("gen3",$desired,$computed);
